language: node_js
sudo: false
node_js:
  - "7"
install:
  - npm install
script:
  - npm run-script babel
  - npm test
  - npm run-script uglify
  - npm run-script upload-coverage
  - npm run-script build-html