language: node_js
sudo: false
node_js:
  - "7"
install:
  - npm install
script:
  - npm run-script babel
  - npm test
  - npm run-script jshint
  - npm run-script uglify-for-hosting
  - npm run-script build-html